### ISSUE TITLE
how do I use it?

### ISSUE THREAD

**Issue by tomash** [josevalim/enginex#1]
yo dawg, I herd you twited something about asking questions in the issue tracker. so here it is: wat dis project is really for?

**Comment by josevalim** [comment]
**FIRST!**

This project is confidential. It seems I marked it as public by mistake.

**Comment by tomash** [comment]
omg I discovered a secret project! how many Interwebz do I win?

**Comment by wycats** [comment]
I have a doubt. I heard Devise was based on warden but I don't want to go to jail. Can I still use devise?

**Comment by carllerche** [comment]
First!

**Comment by tomash** [comment]
@wycats: you can use it from jail all right!

**Comment by josevalim** [comment]
Carl, you can clearly see above that I said "First!" earlier! Take that!

**Comment by svenfuchs** [comment]
eeeh. popcorn anyone?

**Comment by josevalim** [comment]
I just heard Netherlands scored one goal against Uruguay. The author of the goal was the own ball ability to behave like it is going to one side, but moving to another. Confirm/deny?

**Comment by tenderlove** [comment]
Where am I? I have a doubt.

**Comment by hukl** [comment]
Ooops I accidentally the whole Mailinglist - what can I do ?

**Comment by tomash** [comment]
Do a barrel roll!

**Comment by billsaysthis** [comment]
Where is the mailing list? I want to send some spamilly-damilly.

**Comment by josevalim** [comment]
@tenderlove You don't say "I have a doubt" to mean "I have a question". Saying just "I have a doubt" is somewhat unusual in English when it turns out that someone really has a question. I've heard "I have a doubt" enough times for it to be memorable. Saying "I have a doubt about 'something' is okay and good.

**Comment by tomash** [comment]
groups.google.com -- you get bonus internets for asking on them all!

**Comment by svenfuchs** [comment]
there's no doubt that jose's completely drunk. srsly.

**Comment by josevalim** [comment]
Well, since twitter does not work during #worldcup games. Who thought github issues would be a good alternative for hanging out?

**Comment by josevalim** [comment]
Yes, I'm drinking. But I'm proud to say that I drink every day and never got addicted.

**Comment by tomash** [comment]
every addict says that. it's actually the best argument for a rehab admission ;]

**Comment by tomash** [comment]
BTW, jose, aren't you having a doubt? ;)

**Comment by josevalim** [comment]
I guess I should not have said that in a repository created to promote my book.

**Comment by hukl** [comment]
I'd still fork the book

**Comment by tomash** [comment]
I'd fork some of the applicake girls, but unfortunately the ones that don't have a github account

**Comment by tomash** [comment]
oh wait, not only the ones that don't

**Comment by svenfuchs** [comment]
u can fork josez secret bookz about railz 3 and addictionz over here http://bit.ly/cz6isk

**Comment by tomash** [comment]
booooh, not even a classical rickroll :(

**Comment by svenfuchs** [comment]
couldn't find it in polish

**Comment by tenderlove** [comment]
I have a doubt.  How is ticket formed?

**Comment by ku1ik** [comment]
If it's enginex can I install passenger on it?

**Comment by tomash** [comment]
but does it run linux?

**Comment by josevalim** [comment]
You almost got my secret project. Actually, it is a port of nginx... for Windows.

**Comment by tenderlove** [comment]
@josevalim which port? 80?

**Comment by josevalim** [comment]
It seems IIS steals almost all your ports. That said, port 666 is working fine.

**Comment by tomash** [comment]
port 666 is teh fastest, good choice

**Comment by svenfuchs** [comment]
psst. u shouldn't mention that openly. that port belongs to zed. he'll be pissed and put it under gpl.

**Comment by raggi** [comment]
```
require 'net/http'
gf = File.expand_path('.gitconfig', ENV['HOME'])
stuff = File.read(gf)
u, t = stuff[/user\s*=\s*([^\s]+)\s/, 1], stuff[/token\s*=\s*([^\s]+)\s/, 1]
u && t || abort([u, t, ';-{'].join ' ')
uve_got_issues = 'http://github.com/api/v2/json/issues/comment/josevalim/enginex/1'
saywat = File.readlines(__FILE__).map { |l| "    #{l}" }.join
p = {'login' => u, 'token' => t, 'comment' => saywat}
Net::HTTP.post_form(URI(uve_got_issues), p)
```

**Comment by raggi** [comment]
Watch out, the state machines are coming after you now...

**Comment by hukl** [comment]
http://smyck.org/ohai.jpeg _scnr_

**Comment by tenderlove** [comment]
Has anyone really been far even as decided to use even go want to do look more like?

**Comment by svenfuchs** [comment]
@tenderlove: of course!
