### ISSUE TITLE
Running rake tasks from the dummy app

### ISSUE THREAD

**Issue by mjankowski** [josevalim/enginex#12]
In the tests for my engine, I want to drop/create/migrate (ie, db:reset) the database of the dummy rails app with every test run - is it possible to expose the rake tasks from that app up to the Rakefile of the engine itself, or is there a better way to do that?

**Comment by josevalim** [comment]
Just load the app rakefile in the engine rakefile, then you can access all these tasks.

**Comment by mjankowski** [comment]
Thanks, doing an...

import 'test/dummy/Rakefile' got me all the tasks.

I'm having issues with using some of the db: tasks, but I think it's related to something weird I'm attempting with gem loading.
