### ISSUE TITLE
Maybe you should change the name

### ISSUE THREAD

**Issue by ritchiey** [josevalim/enginex#13]
EngineX would be a great name except that it will be confused with the nginx webserver which is pronounced identically.

**Comment by josevalim** [comment]
There is no need to worry about the name anymore. It will be merged into Rails 3.1 simply as `rails plugin new`. :)

Thanks for the feedback!

**Comment by ritchiey** [comment]
Sweet. Actually, after I wrote that I realised I was making a big assumption as to how you pronounce EngineX :)

**Comment by josevalim** [comment]
I think you have assumed it right. :)
