### ISSUE TITLE
The generator does not add the respond_to :html, :xml

### ISSUE THREAD

**Issue by geoffd123** [josevalim/enginex#17]
When I run the scaffold generator it does not add the line:

respond_to :html, :xml

At the top of the controller.  The first time you access the controller it throws an error that this line is missing.

It is a great tool and I am enjoying the book.

Cheers

**Comment by geoffd123** [comment]
Sorry, this should have been posted in the Responders github

**Comment by josevalim** [comment]
No problem! Glad you are enjoying the book!
