### ISSUE TITLE
How to add cucumber?

### ISSUE THREAD

**Issue by millisami** [josevalim/enginex#2]
Currently it has options for test_unit and rspec.
How can I use cucumber too for testing??

**Comment by josevalim** [comment]
You will have to setup on your own. Please check spec_helper or test_helper for more info. :)

**Comment by millisami** [comment]
I forked it and tried to implement.
But I am kinda lost coz I am not a ruby expert.
I have written the test, but couldn't figure out how can I generate the files necessary for the app? Like the command `rails g cucumber:install` generates a bunch of files and directories, I couldn't find out where to run that generator?
I've pushed a forked branch at http://github.com/millisami/enginex/tree/cucumber
Can you plz provide me some way how to get it work?

**Comment by millisami** [comment]
Well again I checked the spec_helper, but still couldn't figure it out how to generate the cucumber files?

**Comment by josevalim** [comment]
Sorry, but I don't have the time and I'm not that familiar with cucumber to help you go further. I dont intend to support cucumber by default in enginex as well.
