### ISSUE TITLE
undefined local variable or method 'dep' in ruby 1.9.2

### ISSUE THREAD

**Issue by pedrodelgallego** [josevalim/enginex#20]
Hi Jose, 

I have the following error using ruby 1.9.2, but using 1.8.7 everything works ok. 

``` sh
~/work/conferize% rvm use 1.9.2
Using /home/pdelgallego/.rvm/gems/ruby-1.9.2-p180

~/work/conferize% enginex conferize_test         
/home/pdelgallego/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems.rb:283:in `activate_spec': undefined local variable or method `dep' for Gem:Module (NameError)
    from /home/pdelgallego/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:49:in `block in require'
    from /home/pdelgallego/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:48:in `each'
    from /home/pdelgallego/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:48:in `require'
    from /home/pdelgallego/.rvm/gems/ruby-1.9.2-p180/gems/enginex-0.8.1/lib/enginex.rb:2:in `<top (required)>'
    from /home/pdelgallego/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:53:in `require'
    from /home/pdelgallego/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:53:in `require'
    from /home/pdelgallego/.rvm/gems/ruby-1.9.2-p180/gems/enginex-0.8.1/bin/enginex:4:in `<top (required)>'
    from /home/pdelgallego/.rvm/gems/ruby-1.9.2-p180/bin/enginex:19:in `load'
    from /home/pdelgallego/.rvm/gems/ruby-1.9.2-p180/bin/enginex:19:in `<main>'
```

BTW congrats on your book, I am enjoying it a lot.

**Comment by josevalim** [comment]
Glad that you are enjoying the book!

Line 2 in Enginex in simply doing a require on ActiveSupport. This leads me to believe this is rather a rubygems bug. Which rubygems version are you using? Have you tried updating it?

**Comment by pedrodelgallego** [comment]
I am using rubygem 1.7.2.  That is the latest stable version.  I am running on ubuntu.

**Comment by josevalim** [comment]
Some people have reported issues on Rubygems 1.7.x and 1.6.x. Could you please try 1.5.x?

**Comment by pedrodelgallego** [comment]
is there an easy way to specify the rubygem that I want to use? I dont see anything in gem --help

**Comment by josevalim** [comment]
Try this: http://stackoverflow.com/questions/523993/how-do-you-downgrade-rubygems

**Comment by pedrodelgallego** [comment]
With rubygem 1.5.0 works! 

I guess I will go and report to the rubygem guys. 

Now I can continue with chapter 5 :)

**Comment by jwang** [comment]
As an FYI, upgrading to rubygems 1.8.5 gives a different error of
`raise_if_conflicts': can't activate activesupport-3.0.1, already activated activesupport-3.0.9 (Gem::LoadError)`

Wonder if there's a better way around it than downgrading to 1.5.x of rubygems.
