### ISSUE TITLE
activesupport error

### ISSUE THREAD

**Issue by mattfordham** [josevalim/enginex#23]
Upon running 'enginex my_engine' I get the following:

/Users/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems.rb:268:in `activate': can't activate activesupport (= 3.0.6) for [], already activated activesupport-3.0.9 for [] (Gem::LoadError)
from /Users/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:50:in`block in require'
from /Users/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:48:in `each'
from /Users/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:48:in`require'
from /Users/matt/.rvm/gems/ruby-1.9.2-p180/gems/enginex-0.8.1/lib/enginex.rb:2:in `<top (required)>'
from /Users/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in`require'
from /Users/matt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
from /Users/matt/.rvm/gems/ruby-1.9.2-p180/gems/enginex-0.8.1/bin/enginex:4:in`<top (required)>'
from /Users/matt/.rvm/gems/ruby-1.9.2-p180/bin/enginex:19:in `load'
from /Users/matt/.rvm/gems/ruby-1.9.2-p180/bin/enginex:19:in`<main>'

I have both activesupport 3.06 and 3.09 installed. Any ideas? Thanks!

**Comment by mattfordham** [comment]
Removing old versions of Rails fixed it.

**Comment by josevalim** [comment]
Yes, this is weird. looks like a rubygems bug. :(
