### ISSUE TITLE
enginex doesn't like projects with hyphens in the name

### ISSUE THREAD

**Issue by contentfree** [josevalim/enginex#28]
I have a project in a directory `fiddleback-shared`. During the initial generation, lib/fiddleback_shared.rb is generated but the module is named `Fiddleback-shared` (instead of `FiddlebackShared`).

This happens in various other places, too: test/fiddleback_shared_test.rb contained `class Fiddleback-sharedTest`

**Comment by josevalim** [comment]
Pull request with a fix please? :)
