### ISSUE TITLE
assets RoutingErrors when running Dummy app w Rails 3.10

### ISSUE THREAD

**Issue by ghost** [josevalim/enginex#33]
## everything run smoothly ... just  the 2 routing errors

Started GET "/" for 127.0.0.1 at 2011-09-21 12:04:15 +0200
  Processing by ContactFormsController#new as HTML
Rendered contact_forms/new.html.erb within layouts/application (16.8ms)
Completed 200 OK in 62ms (Views: 61.6ms | ActiveRecord: 0.0ms)

Started GET "/javascripts/application.js" for 127.0.0.1 at 2011-09-21 12:04:16 +0200
...
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js")
..
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"

**Comment by josevalim** [comment]
Thanks for the report but enginex has been merged into Rails 3.1 and the current version is for Rails 3.0 only. Just use `rails plugin new` instead in 3.1.
