### ISSUE TITLE
app/helpers not included

### ISSUE THREAD

**Issue by ardavis** [josevalim/enginex#34]
I am using enginex with rails 3.0.8 (also tried 3.0.10, same problem). In the test\dummy\ I have a home page that calls a helper method.

This helper lies in my_gem\app\helpers

For some reason, the helper is being considered an 'undefined method'. I am trying to follow your Crafting Rails Applications procedure. What shocks me is that I do have `require 'my_app'` in my config\application.rb

Am I missing something?

Thanks!
Andy

**Comment by josevalim** [comment]
If I am not mistaken, it was a limitation fixed in Rails 3.1. You need to manually include your engine helpers in 3.0.

**Comment by ardavis** [comment]
Thanks much!

**Comment by josevalim** [comment]
You need to call `helper FooHelper` explicitly in your controller.
