### ISSUE TITLE
undefined method `has_selector?

### ISSUE THREAD

**Issue by millisami** [josevalim/enginex#5]
I generated a bare engine via the executable with the rspec option.
And I added one controller spec where I am asserting `response.should have_selector("h1", :content => "hello")`
But it blows up. Do I need to require anything seperately?

```
Failures:
  1) MeroCms::PagesController GET 'pages' should be successful
     Failure/Error: response.should have_selector("h1", :content => "hello")
     undefined method `has_selector?' for #<ActionController::TestResponse:0x10375afb8>
     # ./spec/controllers/pages_controller_spec.rb:11
     # /Users/millisami/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `inject'
```

**Comment by carlosantoniodasilva** [comment]
The have_selector matcher is from Webrat, not from Capybara, so you'd be able to use it inside your tests.

**Comment by millisami** [comment]
I did add the webrat, after posting this, in Gemfile and it worked. Thanks for the reply.
So, is there any reason just to add Capbara, and not webrat, in the enginex generator??

**Comment by carlosantoniodasilva** [comment]
Good to know it's working. Yes, the reason is that we just use Capybara in our projects instead of Webrat, so the tool by default uses it =).

**Comment by millisami** [comment]
Ok. So, what you do if you've to test the view and wanted to use that `have_selector(...)` method with capybara? Is there already existing capybara extensions or do you write it yourself?
Just curious to know coz I want to really use capybara with this.

**Comment by carlosantoniodasilva** [comment]
We use the have_css and have_xpath methods, but you'd need to include Capybara inside the controller tests I believe. But we usually write integration tests, not controller ones, they are better to test the application.

**Comment by millisami** [comment]
Thanks for the reply.
One more question though, do you use rspec to test the Rails3 generators?
Is there anything inside the enginex to test the generator with Rspec2?

**Comment by carlosantoniodasilva** [comment]
There is nothing in enginex to test generators, but I found this post today about it: http://nicksda.apotomo.de/2010/09/getting-a-bloody-rails-3-generator-running-and-testing-it/
It does not use Rspec, but is a great start.

**Comment by millisami** [comment]
Thanks, i'll look into it.
