### ISSUE TITLE
comments on default usage

### ISSUE THREAD

**Issue by jackdempsey** [josevalim/enginex#6]
hey Jose,

Was looking into building some mountable engines for rails 3.1 tonight and I found this. What would you think of having the default behavior (when nothing is passed in) be to show the banner? I feel like that's more helpful than throwing an error right away. Maybe it's just me, but my default action when testing out a new command is to just run it on it's own. 

Anyway, just a thought. Look forward to using this!

**Comment by josevalim** [comment]
+1! :) can you please provide a patch?

**Comment by jackdempsey** [comment]
Definitely! I'm not used to using Thor::Group though, usually just define a help method and have it run by default. This will be a good excuse to learn TG better.

**Comment by josevalim** [comment]
As today it is raising an exception, I believe the best way is to check in the binary itself. Something like:

ARGV.empty? ? Enginex.help : Enginex.start

**Comment by jackdempsey** [comment]
beautiful, thx!

**Comment by jackdempsey** [comment]
Tried this tonight and doesn't seem to be that easy. I used Enginex.banner as help doesn't seem to be defined, but didn't have success with that. Can that really work given how the rest of the actions are setup? It just returned without echoing anything for me.

**Comment by josevalim** [comment]
This is strange, however, I had a better idea, maybe we can simply do this:

```
ARGV << "--help" if ARGV.empty?
Enginex.start
```

This should show the help properly without extra hacks. :)
